export const dataList =  [
  {
    id: 1,
    title: 'บิ็กโคล่า 24 ขวด',
    cuisine: 'บิ็กโคล่า',
    price: 390,
    coverSrc: '/images/drink/cola1.jpg',
  },
  {
    id: 2,
    title: 'เป๊ปซี่ 1.5 ลิตร (แพ็ก 12 ขวด)',
    cuisine: 'เป็บซี่',
    price: 388,
    coverSrc: '/images/drink/cola2.jpg',
  },
  {
    id: 3,
    title: 'บิ๊กโคล่า 1.8 ลิตร (แพ็ก 6 ขวด)',
    cuisine: 'บิ๊กโคล่า',
    price: 140,
    coverSrc: '/images/drink/cola3.jpg',
  },
  {
    id: 4,
    title: 'เป๊ปซี่ 325 มล. (แพ็ก 6 กระป๋อง)',
    cuisine: 'เป็บซี่',
    price: 176,
    coverSrc: '/images/drink/cola4.jpg',
  },
  {
    id: 5,
    title: 'เป๊ปซี่ไม่มีน้ำตาล 550 มล. (แพ็ก 24 ขวด)',
    cuisine: 'เป็บซี่',
    price: 428,
    coverSrc: '/images/drink/cola5.jpg',
  },
  {
    id: 6,
    title: 'โค้กขวด 1.5 ลิตร',
    cuisine: 'โค้ก',
    price: 28,
    coverSrc: '/images/drink/cola6.jpg',
  },
  {
    id: 7,
    title: 'โค้กขวด 1.5 ลิตร. (แพ็ก 12 ขวด) ',
    cuisine: 'โค้ก',
    price: 320,
    coverSrc: '/images/drink/cola7.jpg',
  },
  {
    id: 8,
    title: 'เอสโคล่า 1 ลิตร (แพ็ก 12 ขวด)',
    cuisine: 'เอสโคล่า',
    price: 238,
    coverSrc: '/images/drink/cola8.jpg',
  },
  {
    id: 9,
    title: 'บิ๊ก กลิ่นมิกซ์ฟรุ๊ต 322 มล. (แพ็ก 24 ขวด)',
    cuisine: 'บิ็กโคล่า',
    price: 216,
    coverSrc: '/images/drink/cola9.jpg',
  },
  {
    id: 10,
    title: 'บิ๊กโคล่า 1.8 ลิตร (แพ็ก 6 ขวด)',
    cuisine: 'บิ็กโคล่า',
    price: 162,
    coverSrc: '/images/drink/cola10.jpg',
  },
  {
    id: 11,
    title: 'เอส เกรปเบอร์รี่ 515 มล. (แพ็ก 24 ขวด)',
    cuisine: 'เอสโคล่า',
    price: 384,
    coverSrc: '/images/drink/cola11.jpg',
  },
  {
    id: 12,
    title: 'เอสน้ำเขียว 1 ลิตร (แพ็ก 12 ขวด)',
    cuisine: 'เอสโคล่า',
    price: 238,
    coverSrc: '/images/drink/cola12.jpg',
  },
  {
    id: 13,
    title: 'แฟนต้าน้ำส้ม 1.5ลิตร',
    cuisine: 'เเฟนต้า',
    price: 28,
    coverSrc: '/images/drink/cola13.jpg',
  },
  {
    id: 14,
    title: 'แฟนต้าน้ำส้ม 1.5ลิตร (แพ็ก 12 ขวด)',
    cuisine: 'เเฟนต้า',
    price: 305,
    coverSrc: '/images/drink/cola14.jpg',
  },
  {
    id: 15,
    title: 'แฟนต้าน้ำเขียว 330 ม.ล (แพ็ก 12 ขวด)',
    cuisine: 'เเฟนต้า',
    price: 166,
    coverSrc: '/images/drink/cola15.jpg',
  },
];
